[build]
rustflags = [
  "-C", "link-arg=-Wl,-z,relro",
  "-C", "relocation-model=pic",
  "-C", "target-cpu=native",
  "-C", "target-feature=+crt-static",
  "--cfg", "reqwest_unstable",
]

target = "x86_64-unknown-linux-musl"
